### PR TITLE
Upgrade to RevealJS 5.1.0

### PR DESCRIPTION
**Pull request by mraber**
@joshed-io, Hello, I upgraded your work to the latest RevealJS version (5.1.0).

To test it, I started and browsed the example website (`hugo server -s exampleSite`).
I also tried the new features of RevealJS since 4.4.0, like `F1` for help and the new scroll view (`?view=scroll`).

Tell me if there is something else I should do.

### CODE REVIEW

**Comment by joshed-io** [comment]
@mraber Thanks for the contribution! I'll give it a quick review in the next few days and tag the current version before I merge it in so that users of the current version can target that.

**Comment by veljko** [comment]
Hi @joshed-io 
Any chance to merge this pull request?
Thanks

**Comment by joshed-io** [comment]
@veljko Thanks for the reminder 🙏 

@mraber I'll go ahead and merge this in. Thanks again for the contribution.

**Comment by veljko** [comment]
Thank you @joshed-io and @mraber !

**Pull request merged**
